### PR TITLE
preview component added. Ported from LL25.pas

### PR DESCRIPTION
**Pull request by ThomasI-42**
PreviewControl25 tested, but not very extensively. Works for my needs.
Also ported for version26, but not tested yet.

### CODE REVIEW

**Comment by jbartlau** [comment]
@ThomasI-42 Thanks a lot - looks great at a first glance. We will dive a bit deeper and do some tests before merging.

**Comment by eAlacali** [comment]
From me also a thank you, the changes look ok , also first tests were successful and we would merge that next week.
One more request I have, could you name the file "LLPreview26.pas" un-versioned, so LLPreview.pas

**Review by eAlacali — CHANGES_REQUESTED** [review]
From me also a thank you, the changes look ok , also first tests were successful and we would merge that next week.
One more request I have, could you name the file "LLPreview26.pas" un-versioned, so LLPreview.pas

**Comment by jbartlau** [comment]
@ThomasI-42 We'll merge the pull request and change the file name afterwards.

**Comment by ThomasI-42** [comment]
Perfect. I was a little bit slow.
I have planned the changes for today, but have not yet started :-)

**Pull request merged**
